Readme.md
poetry.lock
pyproject.toml
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
redis_benchmarks_specification/test-suites/redis-benchmark-full-suite-1Mkeys-100B.yml
tox.ini
utils/test-requirements.txt
utils/tests/test_builder.py
utils/tests/test_data/api_builder_common.py
utils/tests/test_data/test-suites/redis-benchmark-full-suite-1Mkeys-100B.yml
utils/tests/test_redis_benchmarks_specification.py
utils/tests/test_self_contained_coordinator.py

- Enabled datasink (redistimeseries) on self-contained-coordinator tool. 
- Included testing for the 3 moving parts (api,builder,scc)

Enabled datasink (redistimeseries) on self-contained-coordinator tool

---

poetry.lock
pyproject.toml
redis_benchmarks_specification/__builder__/builder.py
redis_benchmarks_specification/__builder__/schema.py
redis_benchmarks_specification/__common__/env.py
redis_benchmarks_specification/__self_contained_coordinator__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
redis_benchmarks_specification/test-suites/redis-benchmark-full-suite-1Mkeys-100B.yml
tox.ini
utils/tests/test_builder.py
utils/tests/test_data/api_builder_common.py
utils/tests/test_data/test-suites/redis-benchmark-full-suite-1Mkeys-100B.yml
utils/tests/test_schema.py
utils/tests/test_self_contained_coordinator.py

- [fix] Added platform runner info to datasink;  Fixes #20 
- [fix] Added metadata info to datasink; Fixes #19 
- [fix] each build variant is now associated with the proper time-serie in datasink; Fixes #18

Self-contained-coordinator datasink related issues (build variant, runner info, metadata) fixes

---

pyproject.toml
redis_benchmarks_specification/__api__/api.py
redis_benchmarks_specification/__builder__/builder.py
redis_benchmarks_specification/__common__/package.py
redis_benchmarks_specification/__self_contained_coordinator__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
utils/tests/test_builder.py

[fix] Fixed tool-builder non blocking on event stream

---

pyproject.toml
redis_benchmarks_specification/__api__/api.py
redis_benchmarks_specification/__api__/app.py
redis_benchmarks_specification/__api__/schema.py
redis_benchmarks_specification/__builder__/builder.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
utils/tests/test_api.py
utils/tests/test_builder.py
utils/tests/test_data/api_builder_common.py
utils/tests/test_self_contained_coordinator.py

[fix] fixed xack builder check on str vs int

---

poetry.lock
pyproject.toml
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
utils/tests/test_self_contained_coordinator.py

- [fix] consumer groups for self-contained-coordinator should be broken by running_platform; Fixes #28 
- [fix] SETS for testcases:build_variants, platforms, testcases:metric_context_path are missing; Fixes #27

Self-contained-coordinator consumer group fixes and datasink helper setnames now being set to redistimeseries

---

poetry.lock
pyproject.toml
redis_benchmarks_specification/__api__/app.py
redis_benchmarks_specification/__api__/schema.py
redis_benchmarks_specification/__builder__/builder.py
redis_benchmarks_specification/__cli__/__init__.py
redis_benchmarks_specification/__cli__/cli.py
redis_benchmarks_specification/__common__/builder_schema.py
redis_benchmarks_specification/__common__/env.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
redis_benchmarks_specification/test-suites/redis-benchmark-full-suite-1Mkeys-100B.yml
tox.ini
utils/tests/test_api.py
utils/tests/test_builder.py
utils/tests/test_data/api_builder_common.py
utils/tests/test_self_contained_coordinator.py

[add] Added redis-benchmarks-spec-cli trigger tool; Enabling historical data benchmarks triggering

---

pyproject.toml
redis_benchmarks_specification/__builder__/builder.py
utils/tests/test_builder.py

[fix] Fixed docker images unecessary prefetching from hub

---

redis_benchmarks_specification/test-suites/redis-benchmark-full-suite-1Mkeys-1KiB.yml

This PR adds a new redis-benchmark default benchmark suite variation ( with larger data size )

Introduced redis-benchmark-full-suite-1Mkeys-1KiB benchmark variation

---

pyproject.toml
redis_benchmarks_specification/__runner__/__init__.py
redis_benchmarks_specification/__runner__/args.py
redis_benchmarks_specification/__runner__/runner.py
redis_benchmarks_specification/commands/commands.py
utils/tests/test_commands.py

Added setup agnostic cli benchmark runner (solely client): redis-benchmarks-spec-client-runner

---

redis_benchmarks_specification/__runner__/runner.py

After testing with : 
redis-benchmarks-spec-client-runner --db_server_host localhost --db_server_port 6379 --preserve_temporary_client_dirs --client_aggregated_results_folder ./test1
I found that I quickly ran out of 100GB of space. After some investigation, I could see that all the space is occupied by a bunch of stopped docker containers. These containers did not seem to be reused on a subsequent run I started, but rather the list grew. 
Thus, I suggest removing the unused containers automatically upon tear down.

delete the stopped container by default at tear down

---

poetry.lock
pyproject.toml
redis_benchmarks_specification/__api__/app.py
redis_benchmarks_specification/__self_contained_coordinator__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
utils/tests/test_app.py
utils/tests/test_self_contained_coordinator_memtier.py

Enabled to specify redis_proc_start_port on self contained coordinator; Include merge-base commit tests on API trigger

---

pyproject.toml
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

Fixed self_contained_coordinator r.ping() using 6379 port and not redis_proc_start_port

---

poetry.lock
pyproject.toml
redis_benchmarks_specification/__self_contained_coordinator__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

Added consumer-id to self contained coordinator. Enables multi consumers 

---

redis_benchmarks_specification/test-suites/memtier_benchmark-2keys-lua-eval-hset-expire.yml

Included memtier_benchmark-2keys-lua-eval-hset-expire test case for EVAL perf tracking

---

redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

Fixes #87 
It seems that we were deleting "temporary_dir" but not "temporary_dir_client" 
This should be fixed now ..

Fix bug 87

---

redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

The perf profiles were not being deleted and after a few days, they can end up occupying 100s of GBs of space, eventually cloggin up the machines. 
After the profiles are uploaded to S3, they are now deleted.

Fix issue 130

---

redis_benchmarks_specification/__cli__/stats.py
redis_benchmarks_specification/__common__/runner.py
redis_benchmarks_specification/__runner__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/args.py
utils/tests/test_runner.py

cc [ofekshenawa](https://github.com/ofekshenawa)
Given the full CI is failing in here I can confirm that the added tests cover the added logic and it's working as expected. 
This can be easily tested by running:
```
poetry run pytest utils/tests/test_runner.py::test_extract_testsuites
```

Introduced --tests-regex flag to ease the process of running a subsetof tests

---

.github/workflows/validate-spec-fields.yml
pyproject.toml
redis_benchmarks_specification/__cli__/args.py
redis_benchmarks_specification/__cli__/stats.py

This PR ensures all benchmark fields include some minimum fields like command name, group, etc...

 Validated SPEC fields uppon PR and commit 

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1key-zrevrangebyscore-256K-elements-pipeline-1.yml

added support for zrevbyrangescore

added command zrevbyrangescore

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1key-100MB-string-bitfield.yml

added support for bitfield command.

added support for bitfield command.

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-100B-expire-use-case.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-10B-expire-use-case.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-1KiB-expire-use-case.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-4KiB-expire-use-case.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-100B-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-100B.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-10B-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-10B.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-1KiB-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-1KiB.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1key-100MB-string-bitfield.yml

In some test cases we were using "__value__" . 
For example: --command "SET __key__ __value__"
This is a bug, since it does not generate a data pattern with the specified length, but simply assigns the data to the string "__value__". 
We need to replace this with __data__ so that proper data is generated.

Fix value bug

---

Readme.md

Related-to: 
https://github.com/redis/redis-benchmarks-specification/issues/105
https://github.com/redis/redis-benchmarks-specification/issues/104

Added execution and updated installation section to Readme

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1key-zincrby-1M-elements-pipeline-1.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1key-zrank-1M-elements-pipeline-1.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1key-zrem-5M-elements-pipeline-1.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1key-zrevrank-1M-elements-pipeline-1.yml

Adding support for zrevrank, zrank, zincrby and zrem

added support for zrevrank, zrank, zincrby and zrem

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-hash-hmset-5-fields-with-1000B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-1-fields-with-100B-values-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-5-fields-with-100B-values-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-5-fields-with-100B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-string-with-100B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1key-pfadd-4KB-values-pipeline-10.yml

Adjusted the memory requirements for a few test cases.

Fix memory reqs for load stream

---

redis_benchmarks_specification/__runner__/runner.py
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-1-fields-with-100B-values-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-1-fields-with-100B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-5-fields-with-100B-values-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-stream-5-fields-with-100B-values.yml

fixed the load-stream bechmarks such that the memory footprint does not keep growing. 
also adjusted the memory requirements.

fixed the load-stream bechmarks such that the memory footprint does not keep growing. 

---

redis_benchmarks_specification/__cli__/stats.py
redis_benchmarks_specification/__common__/runner.py
redis_benchmarks_specification/__runner__/args.py
redis_benchmarks_specification/__runner__/runner.py
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-string-with-100B-values-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-string-with-100B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-string-with-10B-values-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-string-with-10B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-string-with-1KiB-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-100B-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-100B.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-10B-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-10B.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-1KiB-pipeline-10.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-get-1KiB.yml
utils/tests/test_runner.py

Benchmarks that we can now use on an OSS cluster deployment (It implied that we moved from `--command` to `--ratio` ) :
- memtier_benchmark-1Mkeys-load-string-with-100B-values-pipeline-10.yml
- memtier_benchmark-1Mkeys-load-string-with-100B-values.yml
- memtier_benchmark-1Mkeys-load-string-with-10B-values-pipeline-10.yml
- memtier_benchmark-1Mkeys-load-string-with-10B-values.yml
- memtier_benchmark-1Mkeys-load-string-with-1KiB-values.yml
- memtier_benchmark-1Mkeys-string-get-100B-pipeline-10.yml
- memtier_benchmark-1Mkeys-string-get-100B.yml
- memtier_benchmark-1Mkeys-string-get-10B-pipeline-10.yml
- memtier_benchmark-1Mkeys-string-get-10B.yml
- memtier_benchmark-1Mkeys-string-get-1KiB-pipeline-10.yml
- memtier_benchmark-1Mkeys-string-get-1KiB.yml
For the benchmarks that use `--command` …

Client runner: enabled oss cluster benchmarks for string (just set and get commands) benchmarks

---

redis_benchmarks_specification/__cli__/cli.py
utils/tests/test_cli.py

Reverting of str converting for timestamp to avoid error 'str object has no attribute timestamp'
Resolves: #209

Update timestamp conversion in client

---

redis_benchmarks_specification/__cli__/cli.py
redis_benchmarks_specification/__cli__/stats.py

Added conversion to avoid error during testing triggering:
```
$ redis-benchmarks-spec-cli --use-branch --from-date 2023-02-11  --redis_port 12010 --redis_host *** --redis_pass *** --redis_user default
Traceback (most recent call last):
File "/home/ubuntu/.local/bin/redis-benchmarks-spec-cli", line 8, in <module>
sys.exit(main())
File "/home/ubuntu/.local/lib/python3.8/site-packages/redis_benchmarks_specification/__cli__/cli.py", line 53, in main
trigger_tests_cli_command_logic(args, project_name, project_version)
File "/home/ubuntu/.local/lib/python3.8/site-packages/redis_benchmarks_specification/__cli__/cli.py", line 259, in trigger_tests_cli_command_logic
) = request_build_from_commit_info(
File "/home/ubuntu/.local/lib/python3.8/site-packages/redis_benchmarks_specification/__common__/b …
```

Added conversion for str for git timestamps

---

redis_benchmarks_specification/__cli__/cli.py
utils/tests/test_cli.py

This change is suggested for consistency of "trigger_tests_cli_command_logic" function on cli.py. 
Added "get_commits_by_tag" and related unit test by analogue with earlier added "get_commits" (renamed to "get_commits_by_branch").

Move getting commits by tags to separate function

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-list-lpop-rpop-with-100B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-list-lpop-rpop-with-1KiB-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-list-with-100B-values.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-load-list-with-1KiB-values.yml

fixed memory reqs, since tests could fail on Sapphire Rappids

fixed memory reqs, since tests could fail on Sapphire Rappids

---

redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
utils/tests/test_data/test-suites/redis-benchmark-full-suite-1Mkeys-100B.yml

Fix for "TypeError" (see below) includes replacement of exec_init_command function from redis-admin branch to similar (but newer) function in redis-benchmark-specification branch. 
redis-* test syntax was aligned to others tests for passing CI rules 
```Traceback (most recent call last):
File "/root/venv-redis/lib/python3.8/site-packages/redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py", line 560, in process_self_contained_coordinator_stream
execute_init_commands(
File "/root/venv-redis/lib/python3.8/site-packages/redisbench_admin/run/common.py", line 426, in execute_init_commands
cmds = k["init_commands"]
TypeError: string indices must be integers
```
Run on testing host: 
```
$ redis-benchmarks-spec-sc-coordinator --platform-name …
```

Fix for TypeError in self-coordinator

---

pyproject.toml
redis_benchmarks_specification/__self_contained_coordinator__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/build_info.py
redis_benchmarks_specification/__self_contained_coordinator__/runners.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

Added support for mutli-arch benchmark runner.

Enabled arch selection on self-contained-coordinator 

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-hash-hexists.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-hash-hincrby.yml

There difference in file test with test description and "name" in test's description itself. 
Suggest to align tests' names by renaming of files:
$ less memtier_benchmark-1Mkeys-**hash**-hinc**rb**y.yml | grep name
name: memtier_benchmark-1Mkeys-**lhash**-hinc**br**y
$ less memtier_benchmark-1Mkeys-**hash**-hexists.yml | grep name
name: memtier_benchmark-1Mkeys-**lhash**-hexists
Suggested solution - align name in description with file name.

Aligned lhash* test-files' names with name inside file

---

pyproject.toml
redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-decr.yml

Reference:
https://github.com/redis/redis/pull/12250
Simple run:
```
$ redis-benchmarks-spec-client-runner --test memtier_benchmark-1Mkeys-string-decr.yml  --override-memtier-test-time 10
2023-06-18 10:14:24 INFO redis-benchmarks-spec-client-runner (solely client) 0.1.71
2023-06-18 10:14:24 INFO Using test-suites folder dir /home/fco/.local/lib/python3.10/site-packages/redis_benchmarks_specification/test-suites
2023-06-18 10:14:24 INFO Running specific benchmark in 1 files: ['/home/fco/.local/lib/python3.10/site-packages/redis_benchmarks_specification/test-suites/memtier_benchmark-1Mkeys-string-decr.yml']
2023-06-18 10:14:24 INFO There are a total of 1 test-suites in folder /home/fco/.local/lib/python3.10/site-packages/redis_benchmarks_specification/test-suites
2023-06-18 10:14:24 INFO …
```

Include a DECR benchmark covering embstring object

---

redis_benchmarks_specification/test-suites/memtier_benchmark-1key-zset-100-elements-zrangebyscore-all-elements-long-scores.yml

- By analyzing the test we saw that the input key and the benchmark key where different.
- We also saw that the number of elements did not matched.

Fixed memtier_benchmark-1key-zset-100-elements-zrangebyscore-all-elements-long-scores key and prepopulation stage

---

redis_benchmarks_specification/__runner__/runner.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

Opened again from branch created in this repository instead of forked branch.
Probably connected with issue: https://github.com/redis/redis-benchmarks-specification/issues/244.
So far when some check resulted with skipping benchmark, it would keep an empty temporary directory in home directory. Deletion of temporary dir should happen in such situation before continuing to the next benchmark.
This PR moves temporary directory deletion to inner function in process_self_contained_coordinator_stream and invokes it before skipping any benchmark

Move temporary dir deletion to inner function, delete temp dir in skipped benchmarks

---

redis_benchmarks_specification/__builder__/builder.py
redis_benchmarks_specification/__cli__/args.py
redis_benchmarks_specification/__cli__/cli.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

Filipe, 
Added filtering by platform, however not sure how to test it, since it depends on the builder... 
Could you please take a look? 
thanks
Martin

added filtering by platform

---

pyproject.toml
redis_benchmarks_specification/__compare__/compare.py

This PR:
- breaks down the data by regression/improvement and total results
- includes benchmark link on each line of the table

Present detailed tables broken down by regression/improvement and full view on github and cli

---

redis_benchmarks_specification/__common__/spec.py
redis_benchmarks_specification/__self_contained_coordinator__/docker.py
redis_benchmarks_specification/__self_contained_coordinator__/runners.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py
redis_benchmarks_specification/setups/topologies/topologies.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-load-string-with-512B-values.yml
utils/tests/test_data/test-suites/test-memtier-dockerhub-iothreads.yml
utils/tests/test_data/test-suites/topologies.yml
utils/tests/test_runner.py
utils/tests/test_self_contained_coordinator.py
utils/tests/test_self_contained_coordinator_memtier.py
utils/tests/test_spec.py
utils/tests/test_topologies.py

Runs memtier_benchmark, for a keyspace length of 3M keys loading STRINGs in which the value has a data size of 512 Bytes, with 650 clients running sequential SET commands.

Added memtier_benchmark-3Mkeys-load-string-with-512B-values. Included 2,4,8,16,32,64 io-threads setups.

---

redis_benchmarks_specification/__runner__/args.py
redis_benchmarks_specification/__self_contained_coordinator__/runners.py
redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py

By analysing the code, git history and unit tests I *think* that `process_self_contained_coordinator_stream` is now on `redis_benchmarks_specification/__self_contained_coordinator__/self_contained_coordinator.py` file.
This PR moves the filtering logic from `runners.py` to `self_contained_coordinator.py`.

Move topology filtering logic

---

redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-get-with-1KiB-values-400_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-get-with-1KiB-values-40_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-get-with-1KiB-values-pipeline-10-2000_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-get-with-1KiB-values-pipeline-10-400_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-get-with-1KiB-values-pipeline-10-40_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-mixed-20-80-with-512B-values-400_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-mixed-20-80-with-512B-values-pipeline-10-2000_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-mixed-20-80-with-512B-values-pipeline-10-400_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-mixed-20-80-with-512B-values-pipeline-10-5200_conns.yml
redis_benchmarks_specification/test-suites/memtier_benchmark-3Mkeys-string-mixed-50-50-with-512B-values-with-expiration-pipeline-10-400_conns.yml

This PR addresses missing pipeline configurations in memtier_benchmark test suites and adds corresponding non-pipeline variants to ensure comprehensive benchmark coverage.
- **Fixed 7 test suite files** that were missing the `--pipeline 10` argument despite having "pipeline-10" in their filenames
- **Files affected:**
- `memtier_benchmark-3Mkeys-string-get-with-1KiB-values-pipeline-10-*_conns.yml` (3 variants)
- `memtier_benchmark-3Mkeys-string-mixed-20-80-with-512B-values-pipeline-10-*_conns.yml` (3 variants)  
- `memtier_benchmark-3Mkeys-string-mixed-50-50-with-512B-values-with-expiration-pipeline-10-400_conns.yml`
- **Added 3 new test suite files** for non-pipeline benchmarks to complement the existing pipeline variants
- **New files:**
- …

Add missing pipeline params
